### ISSUE TITLE
gui popping up but nothing is happening after i enable the hacks

### ISSUE THREAD

**Issue by SweatyMemer** [ChronesDevelopers/ChronClient#1]
when i enable the hacks in chron client, nothing happens. I don't notice any difference whatsoever.

**Comment by lab350** [comment]
same

**Comment by LDMGamingYT** [comment]
yea same

**Comment by NathanDai5287** [comment]
same

**Comment by cxcubehd** [comment]
Please remember that ChronClient does not support 1.16.10 and 1.16.20 and 1.16.0, but it does support 1.16.1
