### ISSUE TITLE
I am playing on Minecraft bedrock edition and it doesn't work

### ISSUE THREAD

**Issue by haddox100** [ChronesDevelopers/ChronClient#11]

**Comment by Kertorace** [comment]
You may not be running as an administrator

**Comment by Wilbatronic** [comment]
Same and i am running as admin but the hax dont work on my world

**Comment by Kertorace** [comment]
Maybe your game version is not 1.16.1.

**Comment by Kertorace** [comment]
you can download Minecraft at https://cloud.189.cn/t/VZJjy2Y77NBb
