### ISSUE TITLE
Hovering over options gives wrong descriptions.

### ISSUE THREAD

**Issue by john35588** [ChronesDevelopers/ChronClient#3]
![Screenshot (3)](https://user-images.githubusercontent.com/56525183/95770721-118c9700-0c77-11eb-98d9-1e21313edefc.png)
When hovering over an option, the alt text is often wrong.

**Comment by sukoshiotokonoko** [comment]
this also happens to me

**Comment by sukoshiotokonoko** [comment]
oh and does teleport and other do something?
